name: Application CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2
      - name: Build docker compose
        run: docker-compose up -d app-test testingdb redistestdb
      - name: Check lint
        run: docker-compose exec -T app-test mypy . && isort --check-only . && black --check . && flake8 app models tests
      - name: Run tests
        run: make unit_tests
      - name: Take down containers
        run: make stop
